### ISSUE TITLE
Add fuux library to libraries list

### ISSUE THREAD

**Issue by henriquecustodia** [afonsopacifer/awesome-flexbox#23]
Hello, 
I'm developing a flexbox library based on angular-material style. This library is just to structure any layout, so it hasn't any style.
Can you take a look and maybe add to library list, if it is useful for anyone?
https://github.com/henriquecustodia/flex-boy

The library is under development, I have to implement many things yet but it is on Alpha version.

Thanks

**Comment by afonsopacifer** [comment]
Sorry for delay :)
Great project, 
can you send a PR?

**Comment by henriquecustodia** [comment]
Sure!
